version: '3.1'

services:
  blogMathSena: 
    container_name: blogMathSena
    hostname: blogMathSena
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: senha
      POSTGRES_DB: blogMathSena
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ~/.PostgressData/postgresonly/blogMathSena:/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
